config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: [:show, :new, :create, :update, :index] do
    get :unread, on: :collection
  end

  resources :feedbacks, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :itineraries, only: [:show, :new, :create, :edit, :update, :destroy, :index, :search] do
    post :search, on: :collection
    resources :build
  end

  resources :notifications, only: :index

  resources :users, constraints: { id: /[A-Za-z0-9\.]+/ }, only: [:show, :update, :destroy] do
    get :itineraries, on: :member
    resources :references, only: [:show, :new, :create, :update, :index]
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  mount Resque::Server, at: '/resque' if defined?(Resque::Server)

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :policy, to: 'pages#policy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  get :fbjssdk_channel, to: 'pages#fbjssdk_channel'
  post :report_uri, to: 'pages#report_uri'
end

app/models/itineraries/search.rb
module Itineraries
  class Search
    include ::ActiveModel::Model

    attr_accessor :from, :to,
                  :start_location_lat, :start_location_lng, :end_location_lat, :end_location_lng,
                  :filter_round_trip, :filter_pink, :filter_verified, :filter_smoking_allowed, :filter_pets_allowed, :filter_driver_gender

    validates :from, presence: true
    validates :to, presence: true
  end
end

app/models/itinerary.rb
class Itinerary
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Mongoid::Geospatial
  include Mongoid::MultiParameterAttributes
  include Mongoid::Slug

  include Concerns::GmapRoute

  DAYNAME = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)

  belongs_to :user
  delegate :name, to: :user, prefix: true
  delegate :first_name, to: :user, prefix: true

  has_many :conversations, as: :conversable, dependent: :destroy

  # Details
  field :description
  field :num_people, type: Integer
  field :smoking_allowed, type: Boolean, default: false
  field :pets_allowed, type: Boolean, default: false
  field :fuel_cost, type: Integer, default: 0
  field :tolls, type: Integer, default: 0
  field :pink, type: Boolean, default: false
  field :round_trip, type: Boolean, default: false
  field :leave_date, type: DateTime
  field :return_date, type: DateTime
  field :daily, type: Boolean, default: false

  # Cached user details (for filtering purposes)
  field :driver_gender
  field :verified

  attr_accessor :share_on_facebook_timeline

  slug :start_address, :end_address, reserve: %w(new)

  # default_scope -> { any_of({:leave_date.gte => Time.now.utc}, {:return_date.gte => Time.now.utc, round_trip: true}, { daily: true }) }

  validates :description, length: { maximum: 1000 }, presence: true
  validates :num_people, numericality: { only_integer: true, greater_than: 0, less_than: 10 }, allow_blank: true
  validates :fuel_cost, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 10_000 }
  validates :tolls, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 10_000 }
  validates :leave_date, timeliness: { on_or_after: -> { Time.current } }, on: :create
  validates :return_date, presence: true, if: -> { round_trip }

  validate :driver_is_female, if: -> { pink }
  validate :return_date_validator, if: -> { round_trip }

  def return_date_validator
    errors.add(:return_date,
               I18n.t('mongoid.errors.messages.after',
                      restriction: leave_date.strftime(I18n.t('validates_timeliness.error_value_formats.datetime')))) if return_date && return_date <= leave_date
  end

  def driver_is_female
    errors.add(:pink, :driver_must_be_female) unless user.female?
  end

  before_create do
    self.driver_gender = user.gender
    self.verified = user.facebook_verified
    true
  end

  after_create do
    ShareOnFacebookTimelineJob.perform_later(id.to_s) if share_on_facebook_timeline
  end

  def title
    [start_address, end_address].join ' - '
  end

  def to_s
    title || id
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  before_action :set_itinerary, only: [:show]
  before_action :check_gender, only: [:show]

  before_action :check_permissions

  def new
    @itinerary = Itinerary.new
  end

  def index
    # @itineraries = Itinerary.includes(:user).all
  end

  def show
    @conversation = @itinerary.conversations.find_or_initialize_by(user_ids: [current_user.id, @itinerary.user.id]) if current_user
    @reference = current_user.references.find_or_initialize_by(itinerary_id: @itinerary.id) if current_user
    session[:redirect_to] = itinerary_path(@itinerary) unless user_signed_in?
  end

  def create
    @itinerary = current_user.itineraries.new(permitted_params.itinerary)
    if @itinerary.save
      redirect_to itinerary_path(@itinerary), flash: { success: t('flash.itineraries.success.create') }
    else
      render :new
    end
  end

  def edit
    @itinerary = current_user.itineraries.find params[:id]
  end

  def update
    @itinerary = current_user.itineraries.find params[:id]
    if @itinerary.update_attributes permitted_params.itinerary
      redirect_to itinerary_path(@itinerary), flash: { success: t('flash.itineraries.success.update') }
    else
      render :edit
    end
  end

  def destroy
    @itinerary = current_user.itineraries.find params[:id]
    @itinerary.destroy
    redirect_to itineraries_user_path(current_user), flash: { success: t('flash.itineraries.success.destroy') }
  end

  def search
    @itineraries = ItinerarySearch.new(params[:itineraries_search], current_user).itineraries
  end

  protected

  def check_permissions
  end

  def set_itinerary
    @itinerary = Itinerary.find params[:id]
  end

  def check_gender
    return unless @itinerary.pink?
    if !user_signed_in?
      redirect_to root_path
    elsif current_user.male?
      redirect_to :dashboard, flash: { error: t('flash.itineraries.error.pink') }
    end
  end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
  def boolean_options_for_select
    @boolean_options_for_select ||= [[t('boolean.true'), true], [t('boolean.false'), false]]
  end

  def default_leave_date
    @default_leave_date ||= (Time.current).change(min: (Time.current.min / 10) * 10) + 10.minutes
  end

  def boolean_tag(value, field)
    status = value ? 'allowed' : 'forbidden'
    content_tag :span, t(".#{field}.#{status}"), class: "tag tag-#{status}"
  end

  def share_on_facebook_timeline_checkbutton(form)
    publish_actions_permission = current_user.facebook_permission?(:publish_actions)
    if background_jobs_available?
      (form.label :share_on_facebook_timeline, class: "btn btn-fb btn-checkbox#{' disabled' unless publish_actions_permission}" do
        form.check_box(:share_on_facebook_timeline, disabled: !publish_actions_permission, checked: publish_actions_permission) +
        content_tag(:span, nil, class: 'fa fa-square-o check') + ' ' +
        Itinerary.human_attribute_name(:share_on_facebook_timeline)
      end) +
        unless publish_actions_permission
          content_tag(:p, class: 'text-muted') do
            content_tag(:small) do
              content_tag(:span, nil, class: 'fa fa-ban') + ' ' +
                t('.missing_publish_actions_permission', appname: APP_CONFIG.app_name)
            end
          end
        end
    else
      t('.share_on_timeline_unavailable', appname: APP_CONFIG.app_name)
    end
  end
end

app/views/itineraries/_form.html.slim
fieldset#single
  = f.input :leave_date, as: :datetime, default: default_leave_date, start_year: Time.now.year, end_year: 1.year.from_now.year, minute_step: 10, ampm: t('time.ampm'), input_html: { class: 'date-time' }, wrapper: :horizontal_form
  = f.input :round_trip, as: :boolean, wrapper: :horizontal_boolean
  = f.input :return_date, as: :datetime, default: default_leave_date, start_year: Time.now.year, end_year: 1.year.from_now.year, minute_step: 10, ampm: t('time.ampm'), input_html: { class: 'date-time' }, disabled: !@itinerary.round_trip, wrapper: :horizontal_form
  = f.input :fuel_cost, wrapper: :horizontal_form do
    .input-group.input-group-number
      = f.text_field :fuel_cost, class: 'form-control'
      span.input-group-addon= APP_CONFIG.currency
  .row
    .col-sm-10.col-sm-offset-2
      p.help-block#fuel-help data-avg-consumption=current_user.vehicle_avg_consumption
        span#fuel-help-text
  = f.input :tolls, wrapper: :horizontal_form do
    .input-group.input-group-number
      = f.text_field :tolls, class: 'form-control'
      span.input-group-addon= APP_CONFIG.currency
    - if @itinerary.errors.include?(:tolls)
      span.help-inline
        = @itinerary.errors.messages[:tolls].join(', ')
  = f.input :description, as: :text, input_html: { rows: 5 }, hint: t('.description_hint'), wrapper: :horizontal_form
  .form-group
    .col-sm-10.col-sm-offset-2
      - if current_user.female?
        = f.input :pink, as: :boolean, hint: t('.pink_hint'), wrapper: false
      = f.input :smoking_allowed, as: :boolean, wrapper: false
      = f.input :pets_allowed, as: :boolean, wrapper: false

/
  fieldset#daily.hide.mock
    .control-group
      .controls
        table.table.table-condensed#daily-itinerary-table
          thead
            tr
              th
              th= t('.day')
              th= t('.leave_time')
              th= t('.return_time')
          tbody
            - (0..6).each_with_index do |index|
              tr
                td
                  p.text-center
                    = check_box_tag "day-#{index}"
                td= label_tag "day-# index ", t('date.day_names')[index]
                td
                  = time_select 'one', 'two', { minute_step: 10, default: { hour: 8 }, ampm: t('time.ampm') }, class: 'date-time', disabled: (index > 0)
                td
                  = time_select 'one', 'two', { minute_step: 10, default: { hour: 18 }, ampm: t('time.ampm') }, class: 'date-time', disabled: (index > 0)
          tfoot
            tr
              td colspan="2"
              td colspan="2"
                = label_tag 'edit-all-times', class: 'checkbox inline' do
                  = check_box_tag 'edit-all-times', nil, checked: true
                  = t('.edit_all_times')

/
  .control-group.hide
    .controls
      = label_tag nil, class: 'radio inline' do
        = f.input, :daily, false, as: :radio, checked: true
        = t('.single_itinerary')
      | &nbsp;
      = label_tag nil, class: 'radio inline mock' do
        = f.default_tag :radio_button, :daily, true, class: 'inline'
        = t('.daily_itinerary')

app/views/itineraries/_header.html.slim
.page-header
  h1.no-margin-bottom= @itinerary.title
.row.itinerary-header
  .col-sm-6
    = image_tag @itinerary.static_map, class: 'google-static-map img-responsive', alt: ''
  .col-sm-6
    .media#user-media
      = link_to user_path(@itinerary.user), class: 'pull-left' do
        = user_profile_picture @itinerary.user, style: 'media-object'
      .media-body
        h4.media-heading
          - if user_signed_in?
            = link_to @itinerary.user, user_path(@itinerary.user)
          - else
            = t('.app_user', appname: APP_CONFIG.app_name)
        <p class="pre-line">#{@itinerary.description}</p>
    .tag-list
      span.tag.tag-icare= Itinerary.human_attribute_name :start_address
      span.tag= @itinerary.start_address
    .tag-list
      span.tag.tag-icare= Itinerary.human_attribute_name :end_address
      span.tag= @itinerary.end_address
    - if @itinerary.daily?
    - else
      .tag-list
        span.tag.tag-icare= Itinerary.human_attribute_name :leave_date
        span.tag= l(@itinerary.leave_date, format: :long)
      - if @itinerary.round_trip?
        .tag-list
          span.tag.tag-icare= Itinerary.human_attribute_name :return_date
          span.tag= l(@itinerary.return_date, format: :long)
    .tag-list
      span.tag.tag-icare= t('.expenses_to_share')
      span.tag #{Itinerary.human_attribute_name(:fuel_cost)}: #{@itinerary.fuel_cost}#{APP_CONFIG.currency}
      span.tag #{Itinerary.human_attribute_name(:tolls)}: #{@itinerary.tolls}#{APP_CONFIG.currency}
    .tag-list
      - if @itinerary.pink?
        span.tag.tag-pink rel='tooltip' title=t('itineraries.form.pink_hint')
          span.fa.fa-lock<>
          = Itinerary.human_attribute_name(:pink)
      = boolean_tag @itinerary.smoking_allowed?, 'smoking'
      = boolean_tag @itinerary.pets_allowed?, 'pets'

app/views/itineraries/_opengraph_head_contents.html.slim
- content_for :head do
  - fb_namespace = APP_CONFIG.facebook.namespace
  meta property='fb:app_id' content=APP_CONFIG.facebook.app_id
  meta property='og:url' content=itinerary_url(itinerary)
  meta property='og:site_name' content=APP_CONFIG.app_name
  meta property='og:type' content="#{fb_namespace}:itinerary"
  meta property='og:title' content=itinerary.title
  meta property='og:image' content=itinerary.static_map
  meta property='og:description' content=itinerary.description
  meta property="#{fb_namespace}:route_start_location:latitude" content=itinerary.start_location.lat
  meta property="#{fb_namespace}:route_start_location:longitude" content=itinerary.start_location.lng
  meta property="#{fb_namespace}:route_end_location:latitude" content=itinerary.end_location.lat
  meta property="#{fb_namespace}:route_end_location:longitude" content=itinerary.end_location.lng
  - for point in itinerary.sample_path
    meta property="#{fb_namespace}:route_sample_path:latitude" content=point[0]
    meta property="#{fb_namespace}:route_sample_path:longitude" content=point[1]

app/views/itineraries/_route_step.html.slim
.row
  .col-sm-4
    = f.input :start_address
    = f.input :end_address
    .form-group
      = f.input :avoid_highways, as: :boolean, wrapper: false
      = f.input :avoid_tolls, as: :boolean, wrapper: false
    .form-group= f.button :button, t('.get_route'), type: 'button', class: 'btn btn-primary', id: 'get-route'
    = image_tag 'ajax-spinner-24x17.gif', width: 24, height: 17, alt: '...', id: 'itineraries-spinner', class: 'hide'
    #error.alert.alert-danger
    #result.alert.alert-info
      = t('.distance')
      b#distance<
      br
      = t('.duration')
      b#duration<
  .col-sm-8
    #new-itinerary-map.google-maps
    p#route-helper.hide
      small
        = Itinerary.human_attribute_name :start_location
        b#from-helper
        br
        = Itinerary.human_attribute_name :end_location
        b#to-helper
        br
        span#copyrights
.row
  .col-sm-4
    h3
      span.fa.fa-eye-slash<>
      = t('.hint_privacy_title')
    p
      = t('.hint_privacy_content')
  .col-sm-4
    h3
      span.fa.fa-wrench<>
      = t('.hint_customize_title')
    p
      = t('.hint_customize_content')
  .col-sm-4
    h3
      span.fa.fa-search<>
      = t('.hint_search_before_title')
    p
      = t('.hint_search_before_content', search_link: (link_to t('.search_link'), itineraries_path)).html_safe

app/views/itineraries/_search.html.slim
= simple_form_for Itineraries::Search.new, url: search_itineraries_path, method: :post, validate: true, remote: true do |f|
  = f.input :from, label: Itinerary.human_attribute_name(:start_address)
  = f.input :to, label: Itinerary.human_attribute_name(:end_address)
  = link_to '#', class: 'collapse-link collapsed', data: { toggle: 'collapse', target: '#search-form-advanced' } do
    span.fa.fa-chevron-down<>
    = t('.advanced_search')
  #search-form-advanced.collapse
    - if !current_user.female?
      = f.input :filter_pink, as: :boolean, label: Itinerary.human_attribute_name(:pink), hint: t('itineraries.form.pink_hint'), wrapper_class: 'form-group form-group-sm'
    .form-group.form-group-sm
      = f.input :filter_verified, as: :boolean, label: t('.verified_users'), wrapper: false
      = f.input :filter_round_trip, as: :boolean, label: Itinerary.human_attribute_name(:round_trip), wrapper: false
    - for boolean_field in [:smoking_allowed, :pets_allowed]
      = f.input "filter_#{boolean_field}".to_sym, collection: boolean_options_for_select, include_blank: true, label: Itinerary.human_attribute_name(boolean_field), wrapper_class: 'form-group form-group-sm'
    = f.input :filter_driver_gender, collection: options_for_array_collection(User, :gender), include_blank: true, label: Itinerary.human_attribute_name(:driver_gender), wrapper_class: 'form-group form-group-sm'
  .form-group
    = f.hidden_field :start_location_lat
    = f.hidden_field :start_location_lng
    = f.hidden_field :end_location_lat
    = f.hidden_field :end_location_lng
    = f.button :button, t('.search'), class: 'btn btn-primary', id: 'itineraries-search', data: { disable_with: t('helpers.disable_with') }
    = image_tag 'ajax-spinner-24x17.gif', width: 24, height: 17, alt: '...', id: 'itineraries-spinner'

app/views/itineraries/_table.html.slim
.table-responsive
  table.table.table-itinerary
    thead
      tr
        th= Itinerary.human_attribute_name(:start_address)
        th= Itinerary.human_attribute_name(:end_address)
        th
          span.visible-xs
            span.fa.fa-info-circle rel='tooltip' title=t('itineraries.common.features')
          span.hidden-xs= t('itineraries.common.features')
        - if edit
          th= t('helpers.actions')
        - else
          th= User.model_name.human
          th= Itinerary.human_attribute_name(:leave_date)
    tbody
      - for itinerary in itineraries
        tr.vertical-align-middle
          td= link_to itinerary.start_address, itinerary_path(itinerary)
          td= link_to itinerary.end_address, itinerary_path(itinerary)
          td
            - if itinerary.pink
              span.text-pink.fa-fw.fa.fa-lock rel='tooltip' title=Itinerary.human_attribute_name(:pink)
            - if itinerary.daily
              span.fa-fw.fa.fa-repeat rel='tooltip' title=Itinerary.human_attribute_name(:daily)
            - if itinerary.round_trip
              span.fa-fw.fa.fa-exchange rel='tooltip' title=Itinerary.human_attribute_name(:round_trip)
          - if edit
            td
              .btn-toolbar
                = link_to edit_itinerary_path(itinerary), class: 'btn btn-xs btn-default' do
                  span.fa.fa-pencil<>
                  = t('helpers.links.edit')
                = link_to itinerary_path(itinerary), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-xs btn-danger' do
                  span.fa.fa-times<>
                  = t('helpers.links.destroy')
          - else
            td= link_to itinerary.user, user_path(itinerary.user)
            td= l(itinerary.leave_date.in_time_zone, format: :short)

app/views/itineraries/edit.html.slim
- title t('.title')
.container
  == render 'header'
  hr
  = simple_form_for @itinerary, validate: true, html: { class: 'form-horizontal' } do |f|
    == render 'shared/error_messages', object: f.object
    == render 'form', f: f
    .row
      .col-sm-10.col-sm-offset-2
        = f.button :button, class: 'btn btn-primary', data: { disable_with: t('helpers.disable_with') }

app/views/itineraries/index.html.slim
- title t('.title')
.container
  .row
    .col-sm-4
      h3= yield :title
      == render 'search'
      #error.alert.alert-danger
    .col-sm-8
      #index-itineraries-map.google-maps
      #itineraries-thumbs.row

app/views/itineraries/new.html.slim
- title t('.title')
.container
  - if @itinerary.errors.any?
    .alert.alert-danger.fade.in
      button type='button' class='close' data-dismiss='alert' &times;
      h4.alert-heading= t('errors.template.header', model: Itinerary.model_name.human, count: @itinerary.errors.size)
      = t('errors.template.body')
      ul
        - for message in @itinerary.errors.full_messages
          li= message
  .row
    .col-sm-6
      #wizard-step-1-title.itinerary-step.active
        h3= t('.plan_route')
    .col-sm-6
      #wizard-step-2-title.itinerary-step.hidden-xs
        h3= t('.insert_details_and_confirm')
  = simple_form_for @itinerary, validate: true do |f|
    .form-group
      #wizard-step-1-content data-step='1'
        == render 'route_step', f: f
      #wizard-step-2-content data-step='2'
        .row
          .col-sm-4
            = image_tag transparent_gif_image_data, class: 'img-responsive google-static-map', id: 'itinerary-preview-image', alt: ''
          .col-sm-8
            h1.itinerary-title
              small= Itinerary.human_attribute_name :start_address
              span#itinerary-preview-from
              small= Itinerary.human_attribute_name :end_address
              span#itinerary-preview-to
        .form-horizontal== render 'form', f: f
        .text-center= share_on_facebook_timeline_checkbutton(f)
    .form-group.text-center
      = f.hidden_field :route
      = f.hidden_field :via_waypoints
      .btn-toolbar
        = button_tag t('.previous_step'), type: 'button', class: 'btn btn-lg btn-default', name: 'back_button', id: 'wizard-prev-step-button', disabled: true
        = f.submit t('.next_step'), type: 'button', class: 'btn btn-lg btn-primary', name: 'next_button', id: 'wizard-next-step-button', disabled: false
        = f.submit t('.confirm_and_share'), class: 'btn btn-lg btn-primary', id: 'new_itinerary_submit', disabled: true, data: { disable_with: t('helpers.disable_with') }

app/views/itineraries/show.html.slim
- title @itinerary.title
== render 'opengraph_head_contents', itinerary: @itinerary
.container
  == render 'shared/flash_messages'
  == render 'header'
  hr
  .btn-toolbar.text-center
    - if user_signed_in?
      - if current_user != @itinerary.user
        = link_to new_or_show_conversation_path(@conversation), class: 'btn btn-lg btn-primary' do
          span.fa.fa-comment<>
          = t('.contact', user: @itinerary.user_first_name)
        = link_to new_or_show_reference_path(@reference, @itinerary), class: 'btn btn-lg btn-default' do
          span.fa.fa-thumbs-up<>
          = t('.send_reference')
        /
          .btn-group
            button.btn.btn-lg.btn-warning
              span.fa.fa-flag<>
            button.btn.btn-lg.btn-warning.dropdown-toggle data-toggle='dropdown'
              span.caret
            ul.dropdown-menu role='menu'
              li= link_to t('.report_itinerary'), '#'
      - else
        = link_to edit_itinerary_path(@itinerary), class: 'btn btn-lg btn-default' do
          span.fa.fa-pencil<>
          = t('helpers.titles.edit', model: Itinerary.model_name.human)
    - else
      = link_to user_omniauth_authorize_path(provider: :facebook), class: 'btn btn-lg btn-fb', data: { no_turbolink: true } do
        span.fa.fa-facebook-square<>
        = t('.login_to_contact')