config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'pages#home'

  resources :conversations, only: [:show, :new, :create, :update, :index] do
    get :unread, on: :collection
  end

  resources :feedbacks, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :itineraries, only: [:show, :new, :create, :edit, :update, :destroy, :index, :search] do
    post :search, on: :collection
    resources :build
  end

  resources :notifications, only: :index

  resources :users, constraints: { id: /[A-Za-z0-9\.]+/ }, only: [:show, :update, :destroy] do
    get :itineraries, on: :member
    resources :references, only: [:show, :new, :create, :update, :index]
  end

  # Admin Area
  namespace :admin do
    resources :users, only: [:index] do
      get :login_as, on: :member
      post :ban, :unban, on: :member
    end
  end

  mount Resque::Server, at: '/resque' if defined?(Resque::Server)

  # Root route aliases
  get :dashboard, to: 'users#dashboard'
  get :settings, to: 'users#settings'
  get :banned, to: 'users#banned'

  get :about, to: 'pages#about'
  get :how_it_works, to: 'pages#how_it_works'
  get :policy, to: 'pages#policy'
  get :terms, to: 'pages#terms'
  get :demo_terms, to: 'pages#demo_terms'
  get :fbjssdk_channel, to: 'pages#fbjssdk_channel'
  post :report_uri, to: 'pages#report_uri'
end

app/views/shared/_advertising.html.slim
.advertising.alert.alert-info.fade.in
  button type='button' class='close' data-dismiss='alert' &times;
  h4.alert-heading= t('.enterprises')
  = t('.contact_us_html')

app/views/shared/_error_messages.html.slim
- if object.errors.full_messages.any?
  .alert.alert-block.alert-danger.fade.in
    button.close type='button' data-dismiss='alert' &times;
    h4= t('helpers.form.error')
    - for msg in object.errors.full_messages
      = msg
      br

app/views/shared/_flash_messages.html.slim
- for type, message in flash
  .alert.fade.in class="alert-#{twitterized_type(type)}"
    = message

app/views/shared/_footer.html.slim
footer
  .container
    ul.list-inline.list-footer
      li.diowa-footer
        = link_to 'http://diowa.com' do
          = image_tag transparent_gif_image_data, alt: 'diowa', height: 25, width: 80, title: 'diowa', class: 'diowa-logo'
      - if user_signed_in?
        li= link_to t('about'), :about
        li= link_to t('how_it_works'), :how_it_works
        - unless APP_CONFIG.demo_mode
          li= link_to t('terms'), :terms
      li
        span.fa.fa-github<>
        = link_to 'diowa/icare', APP_CONFIG.repository_url
      - if user_signed_in?
        li
          span.fa.fa-bullhorn<>
          = link_to Feedback.model_name.human(count: :lot), feedbacks_url
        - if APP_CONFIG.demo_mode
          li
            = link_to user_path(current_user), method: :delete, class: 'text-danger', data: { confirm: t('helpers.links.confirm') } do
              span.fa.fa-times<>
              = t('delete_account')
      - if APP_CONFIG.demo_mode
        li
          span.fa.fa-warning<>
          = t('demo_mode')

app/views/shared/_modal_why_facebook.en-US.html.slim
#why-facebook.modal.fade tabindex='-1' role='dialog' aria-labelledby=t('why_facebook') aria-hidden=true
  .modal-dialog
    .modal-content
      .modal-header
        button.close type='button' data-dismiss='modal' aria-hidden=true &times;
        h3.modal-title= t('why_facebook')
      .modal-body
        p
          | We know that some people do not use Facebook or do not allow permissions to third party applications.
        p
          | Anyway, the creation of a new profile will you solve a captcha, wait for an activation email, insert
          | personal data, upload at least one picture, select an user name, remember a new password, etc.
          | You can skip all this boring process by logging in with Facebook.
        p
          | Personal identity matters for our application. You should be able to trust your new travel companions and Facebook provides
          | a first verification through friends, friends of friends...
        p
          | Moreover, through Facebook you can find travel companions who share your same interests.
        p
          strong
            | NOTE: We will never post anything without your explicit consent.
      .modal-footer
        = link_to t('close'), '#', 'aria-hidden' => true, data: { dismiss: 'modal' }, class: 'btn btn-primary'

app/views/shared/_modal_why_facebook.it-IT.html.slim
#why-facebook.modal.fade tabindex='-1' role='dialog' aria-labelledby=t('why_facebook') aria-hidden=true
  .modal-dialog
    .modal-content
      .modal-header
        button.close type='button' data-dismiss='modal' aria-hidden=true &times;
        h3.modal-title= t('why_facebook')
      .modal-body
        p
          | Siamo consapevoli che qualcuno non utilizza Facebook oppure non concede volentieri i permessi alle applicazioni di terze parti.
        p
          | La creazione di un nuovo profilo, tuttavia, ti constringerebbe a risolvere un captcha, attendere la
          | mail di attivazione, inserire dati anagrafici, caricare almeno una foto,
          | scegliere un nome utente, ricordare una nuova password, ecc.
          | Accedendo con Facebook è possibile evitare questa noiosa procedura.
        p
          | Inoltre è facile immaginare che l'identità personale per una applicazione come la nostra è fondamentale. Bisogna potersi fidare in qualche modo dei nuovi compagni di viaggio e Facebook permette una prima verifica tramite amici, amici di amici...
        p
          | Tramite Facebook, infine, puoi trovare compagni di viaggio che condividono i tuoi stessi interessi.
        p
          strong
            | NOTA: Non posteremo mai nulla senza il tuo esplicito permesso.
      .modal-footer
        = link_to t('close'), '#', 'aria-hidden' => true, data: { dismiss: 'modal' }, class: 'btn btn-primary'

app/views/shared/_navbar.html.slim
nav.navbar.navbar-fixed-top.navbar-internal.navbar-default role='navigation'
  .container
    .navbar-header
      button.navbar-toggle type='button' data-toggle='collapse' data-target='.navbar-responsive-collapse'
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to user_signed_in? ? :dashboard : root_path, class: 'navbar-brand' do
        = image_tag 'turtle_dark.svg', class: 'navbar-brand-logo'
        span.hidden-xs<= APP_CONFIG.app_name
    - if user_signed_in?
      == render 'shared/notifications'
      .navbar-collapse.collapse.navbar-responsive-collapse role="navigation"
        ul.nav.navbar-nav.navbar-right
          li#navbar-user-info
            = link_to user_path(current_user), class: 'navbar-profile-link' do
              = user_profile_picture current_user, size: nil, style: nil
              span= current_user
          li.dropdown
            = link_to '#', data: { toggle: 'dropdown' }, class: 'dropdown-toggle' do
              span.fa.fa-cog
            ul.dropdown-menu
              li= link_to t('.account_settings'), :settings
              - if current_user.admin?
                li.divider
                li= link_to t('.admin_users'), admin_users_path
              li.divider
              li= link_to t('logout'), destroy_user_session_path, method: :delete
    - else
      .navbar-collapse.collapse.navbar-responsive-collapse role="navigation"
        ul.nav.navbar-nav.navbar-right
          li= link_to t('how_it_works'), :how_it_works
          li= link_to t('about'), :about
          li.dropdown
            = link_to '#', data: { toggle: 'dropdown' }, class: 'dropdown-toggle' do
              = t('lang_native_name')
              span.caret
            ul.dropdown-menu
              - for locale in (I18n.available_locales - [I18n.locale])
                li=link_to t('lang_native_name', locale: locale), url_for(locale: locale)
          li.facebook-link
            = link_to user_omniauth_authorize_path(provider: :facebook), data: { no_turbolink: true } do
              span.fa.fa-facebook-square<>
              = t('login_with_facebook')

app/views/shared/_notifications.html.slim
ul#navbar-notifications.nav.navbar-nav
  = notifications_tag :conversations, 'comments'